# Generated by Django 4.0.4 on 2022-07-02 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено')),
                ('category', models.IntegerField(blank=True, null=True, verbose_name='Категория')),
                ('manufacturer', models.IntegerField(blank=True, null=True, verbose_name='Производитель')),
                ('retailer', models.IntegerField(blank=True, null=True, verbose_name='Ритейлер')),
                ('store_type', models.IntegerField(blank=True, null=True, verbose_name='Тип магазина')),
                ('region', models.IntegerField(blank=True, null=True, verbose_name='Регион')),
                ('store', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мазагин')),
            ],
            options={
                'verbose_name': 'Рекомендованная матрица',
                'verbose_name_plural': 'Рекомендованные матрицы',
            },
        ),
        migrations.CreateModel(
            name='RecommendedAssortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('scu', models.CharField(blank=True, max_length=255, null=True)),
                ('distribution', models.FloatField(blank=True, null=True)),
                ('facing_amount', models.FloatField(blank=True, null=True)),
                ('matrix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assortment', to='assortment.recommendedmatrix')),
            ],
            options={
                'verbose_name': 'Ассортимент рекомендованной матрицы',
                'verbose_name_plural': 'Ассортименты рекомендованных матриц',
            },
        ),
        migrations.CreateModel(
            name='ContractMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Создано')),
                ('start_dt', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата начала действия')),
                ('status', models.SmallIntegerField(choices=[(1, 'Новая'), (2, 'Активная (действующая)'), (3, 'Истекшая')], default=1, verbose_name='Статус матрицы')),
                ('end_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания действия')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено')),
                ('category', models.IntegerField(blank=True, null=True, verbose_name='Категория')),
                ('manufacturer', models.IntegerField(blank=True, null=True, verbose_name='Производитель')),
                ('retailer', models.IntegerField(blank=True, null=True, verbose_name='Ритейлер')),
                ('store_type', models.IntegerField(blank=True, null=True, verbose_name='Тип магазина')),
                ('region', models.IntegerField(blank=True, null=True, verbose_name='Регион')),
                ('store', models.CharField(blank=True, max_length=255, null=True, verbose_name='Магазин')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_matrix', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('recommended_matrix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_matrix', to='assortment.recommendedmatrix', verbose_name='Рекомендованная матрица')),
            ],
            options={
                'verbose_name': 'Контрактная матрицы',
                'verbose_name_plural': 'Контрактные матрицы',
            },
        ),
        migrations.CreateModel(
            name='ContractAssortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('scu', models.CharField(blank=True, max_length=255, null=True)),
                ('target_facings', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('matrix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assortment', to='assortment.contractmatrix')),
            ],
            options={
                'verbose_name': 'Ассортимент контрактной матрицы',
                'verbose_name_plural': 'Ассортименты контрактных матриц',
            },
        ),
    ]
